### ISSUE TITLE
Cannot install module on PHP7.2.20

### ISSUE THREAD

**Issue by duckchip** [pkarsai/show-out-of-stock-products-magento2#2]
Hi there!

First of all, thanks a lot for this open-sourcing this module :) 

I'd like to install this on a Magento 2.3.2 but composer doesn't let me since we have a PHP 7.2.20 composer constrained defined.

Would you be so kind to include this in the composer.json?

thanks a lot!

**Comment by pkarsai** [comment]
Hi,

The restrictions in the composer.json are there because this module was not tested with neither PHP 7.2 nor with Magento 2.3. You can manually install this module if you want – at your own risk – and use it with your configuration, but I won't modify the release version because I don't know if it works with those versions or not.

**Comment by mattyl** [comment]
had same issue - installed via app/code method (ie manually) it seems to work ok
example
https://azuni.co.uk/large-mosaic-drop-earrings
(apologies if the out of stock colour comes back into stock by the time anyone clicks on this...)

PHP 7.2.2 and Magento 2.3.2
